### ISSUE TITLE
Запись на курс «Разработка программного обеспечения для GNU/Linux»

### ISSUE THREAD

**Issue by FrBrGeorge** [FrBrGeorge/LinuxDevelopment2023#1]
Для получения оценки по спецкурсу «[Разработка программного обеспечения для GNU/Linux](https://uneex.org/LecturesCMC/LinuxApplicationDevelopment2021)» просьба в комментариях осталять свои коордминаты в формате

- ФИО
- Группа (если не ВМК, то +название вуза/факультета и т. п.)
- Ссылка на **публичный** git-репозиторий, в котором буду опубликованы решения

**Comment by juliazadorozhnaya** [comment]
Задорожная Юлия Андреевна, группа 321, https://git.cs.msu.ru/s02190029/development-for-linux

**Comment by unishift** [comment]
- Ляпустин Евгений Владиславович
- Группа 622
- https://github.com/unishift/unix-course

**Comment by yukatan1701** [comment]
- Лапенко Юлия Андреевна
- Группа 527
- https://github.com/yukatan1701/LinuxAppDev

**Comment by RuRo** [comment]
- Стоцкий Андрей Владимирович
- Группа 622
- https://gitlab.com/ruro-courses/other/linux-development

**Comment by IzumovaD** [comment]
- Изюмова Дарья Дмитриевна
- Группа 524
- https://github.com/IzumovaD/LinuxDevelopment2021

**Comment by SeTSeR** [comment]
- Макаров Сергей Сергеевич
- Группа 527
- https://git.cs.msu.ru/s02210154/linuxappdevelopment

**Comment by dean1t** [comment]
- Кожемяков Константин Александрович
- Группа 622
- https://github.com/dean1t/LinuxDevelopment2021

**Comment by LittleLovelySun** [comment]
* Кудинова Светлана Дмитриевна
* Группа 528
* https://github.com/LittleLovelySun/LinuxApplicationDevelopment2021.git

**Comment by ImeevMA** [comment]
- Имеев Мерген Анатольевич
- Группа 616
- https://github.com/ImeevMA/LinuxDev2021

**Comment by Hovushka** [comment]
- Феклисов Егор Дмитриевич
- Группа 522
- https://github.com/Hovushka/LinuxApplicationDevelopment2021.git

**Comment by andralet** [comment]
- Цехмистер Александр Андреевич
- Группа 327
- https://github.com/andralet/UNEEX-2021-22

**Comment by Andelme** [comment]
- Малыгин Даниил Константинович
- Группа 523
- https://github.com/Andelme/LinuxApplicationDevelopment2021

**Comment by gregory6316** [comment]
* Нанян Георгий Артурович
* Группа 519/2
* https://github.com/gregory6316/LinuxDev2021

**Comment by ScaryPG** [comment]
- Раенчук Максим Владимирович
- Группа 522
- https://github.com/ScaryPG/LinuxApplicationDevelopment2021

**Comment by dovvakkin** [comment]
* Кожевников Евгений Владимирович
* Группа 524
* https://github.com/dovvakkin/LinuxApplicationDevelopment2021

**Comment by anick2** [comment]
- Аникевич Юлия Вадимовна
- Группа 525
- https://github.com/anick2/LinuxApplicationDevelopment2021

**Comment by Astasiia** [comment]
Широкова Анастасия Сергеевна
Группа 525
https://github.com/Astasiia/Linux

**Comment by sudofind** [comment]
* Коновальчук Дмитрий Сергеевич
* Группа 622
* https://github.com/sudofind/linux_dev

**Comment by Egor-S** [comment]
* Скляров Егор Дмитриевич
* Группа 622
* https://github.com/Egor-S/LinuxDevelopment2021

**Comment by shorohml** [comment]
- Шорошов Григорий Максимович
- группа 622
- https://github.com/shorohml/LinuxAppDev2021

**Comment by de-tolkac** [comment]
- Толкачев Денис Александрович
- группа 425
- https://github.com/de-tolkac/LinuxAppDev2021

**Comment by Prikalel** [comment]
- Поклонский Алексей Андреевич
- Группа 319/2
- https://git.cs.msu.ru/s02190178/linuxapplicationdevelopment2021.git

**Comment by amuShtein** [comment]
- Кочармин Михаил Дмитриевич
- Группа 202
- https://github.com/amuShtein/LinuxAppDev2021

**Comment by augenzu** [comment]
* Стукова Александра Николаевна
* Группа 428
* <https://github.com/augenzu/linux-application-development>

**Comment by luchbheag** [comment]
- Недоливко Юлия Николаевна

- Группа 616

- https://github.com/luchbheag/uneex-course

**Comment by Zikilop** [comment]
- Кочетов Егор Владимирович
- Группа 604
- https://github.com/Zikilop/LinuxAppDev2021

**Comment by Herceg00** [comment]
- Личманов Дмитрий Игоревич
- Группа 523
- https://github.com/Herceg00/GNU_Linux

**Comment by lyuha1504** [comment]
- Уваркин Илья Геннадьевич
- Группа 604
- https://github.com/lyuha1504/unix_course_2021.git

**Comment by KekNow** [comment]
- Тонких Алексей Александрович
- Группа 519/2
- https://github.com/KekNow/SoftwareDevelopmentforGNULinux

**Comment by Lorien2027** [comment]
-  Лисин Никита Олегович
-  Группа 622
-  https://github.com/Lorien2027/LinuxDevelopment2021

**Comment by vekle** [comment]
- Соловьёв Александр Юрьевич
- Группа 523
- https://github.com/vekle/LinuxAppDevelCourse

**Comment by Layvis1998** [comment]
Карандеев Илья Дмитриевич
Группа 403
https://github.com/Layvis1998/Linux_application_dev

**Comment by romko11l** [comment]
-  Лыткин Роман Андреевич
-  Группа 419/2
-  https://gitlab.com/romko11l/linuxapplicationdevelopment2021

**Comment by NargizNargiz** [comment]
- [ ] Кемпирова Наргиз Амановна

- [ ] 623

- [ ] https://github.com/NargizNargiz/LinuxCourse2021

**Comment by ghost171** [comment]
*    Селевенко Роман Михайлович

*    418

*    https://github.com/ghost171/LINUX_programming

**Comment by RychRych** [comment]
Рычкова Любовь Михайловна
Группа 201
https://github.com/RychRych/UnixDevelopment

**Comment by Leksa98** [comment]
Герценштейн Александра Сергеевна
Группа 514
https://github.com/Leksa98/LinuxDevelopment2021

**Comment by SergeyChernykh** [comment]
Черных Сергей Алексеевич
Группа 617
https://github.com/SergeyChernykh/LinuxDevelopment2021

**Comment by MariaMsu** [comment]
Черепнина Мария Сергеевна
Группа 427
https://github.com/MariaMsu/LinuxDevelopment2021

**Comment by CrafterKolyan** [comment]
- Королев Николай Сергеевич
- 617
- https://github.com/CrafterKolyan/linux-application-development

**Comment by vladimirtelepov** [comment]
Телепов Владимир Юрьевич
Группа 620
https://github.com/vladimirtelepov/unix_development

**Comment by VictoriaAutMors** [comment]
Алиханов Тимур Мурадович
группа 418
https://github.com/VictoriaAutMors/LinuxDevelopment2021

**Comment by PetrovIgorA** [comment]
* Петров Игорь Андреевич
* группа М210
* https://github.com/PetrovIgorA/LinuxApplicationDevelopment2021

**Comment by anyaantipina** [comment]
Антипина Анна Вячеславовна
группа М210
https://github.com/anyaantipina/LinuxDevelopment2021

**Comment by MarkGhann** [comment]
* Гонопольский Марк Геннадьевич
* группа М210
* https://github.com/MarkGhann/linux-application-development-2021

**Comment by ololowl** [comment]
- Моргунова Ольга Максимовна
- группа 622
- https://github.com/ololowl/linux-dev2021

**Comment by drwtsn95** [comment]
- Смирнов Алексей Анатольевич
- группа 519
- https://github.com/drwtsn95/unix_dev_course

**Comment by ne-egor** [comment]
Зинкин Егор Владимирович
Группа 618/2
https://github.com/ne-egor/linux_app_dev_21

**Comment by sasasagagaga** [comment]
- Чернышёв Александр Владиславович
- 617
- https://github.com/sasasagagaga/linux-application-development

**Comment by tssasha** [comment]
* Цыс Александра Ивановна
* 427
* https://github.com/tssasha/linux-course

**Comment by ekuptsov** [comment]
- Купцов Евгений Вадимович
- группа 622
- https://github.com/ekuptsov/LinuxApplicationDevelopment2021

**Comment by AnyKeyShik** [comment]
- Гнилозуб-Волобуев Никита Игоревич
- группа 201
- https://gitlab.com/AnyKeyShik/unix-practicum-cmc

**Comment by DenisGZM** [comment]
Герасимов Денис Юрьевич
523
https://github.com/DenisGZM/LinuxAppDev_2021

**Comment by dayyass** [comment]
- Эль-Айясс Дани Валид
- 617
- https://github.com/dayyass/linux-application-development

**Comment by ogoldobina** [comment]
- Голдобина Ольга Игоревна
- 617
- https://github.com/ogoldobina/linux-application-development

**Comment by dukallis** [comment]
- Перевозников Олег Сергеевич
- 504
- https://github.com/dukallis/linux-app-dev2021

**Comment by dbanast** [comment]
- Доброва Анастасия Борисовна
- 624
- https://github.com/dbanast/LinuxApplicationDevelopment2021

**Comment by MetalDream666** [comment]
Копикова Софья Дмитриевна
525
https://github.com/MetalDream666/LinuxApplicationDevelopment2021

**Comment by lizzardhub** [comment]
- Великанов Максим Сергеевич
- Группа 522
- https://github.com/lizzardhub/LinuxApplicationDevelopment2021

**Comment by Visolsti** [comment]
- Романенко Алексей Игоревич
- М210
- https://github.com/Visolsti/LinuxDevelopment2021

**Comment by yura-leb** [comment]
Лебединский Юрий Евгеньевич
Группа 321
https://git.cs.msu.ru/s02190141/linux-2021.git

**Comment by mariyaph** [comment]
Филиппова Мария Анатольевна
Группа 604
https://github.com/mariyaph/LinuxApplicationDevelopment2021

**Comment by aiosadchy** [comment]
Осадчий Александр Ильич
Группа 622
https://github.com/aiosadchy/linux-development-2021
